using System;
using System.Collections.Generic;

namespace Entiti.DB
{
    public partial class Languages
    {
        public Languages()
        {
            AspNetUserLanguages = new HashSet<AspNetUserLanguages>();
            Sites = new HashSet<Sites>();
            TemplateAutogeneratedItems = new HashSet<TemplateAutogeneratedItems>();
            Translations = new HashSet<Translations>();
        }

        public int LanguageId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }

        public ICollection<AspNetUserLanguages> AspNetUserLanguages { get; set; }
        public ICollection<Sites> Sites { get; set; }
        public ICollection<TemplateAutogeneratedItems> TemplateAutogeneratedItems { get; set; }
        public ICollection<Translations> Translations { get; set; }
    }
}
