using System;
using System.Collections.Generic;

namespace Entiti.DB
{
    public partial class Sites
    {
        public Sites()
        {
            BannerSites = new HashSet<BannerSites>();
            LeaguePriority = new HashSet<LeaguePriority>();
            LeagueVisibility = new HashSet<LeagueVisibility>();
            PredefinedCouponSites = new HashSet<PredefinedCouponSites>();
            SportPriority = new HashSet<SportPriority>();
            SportVisibility = new HashSet<SportVisibility>();
            TemplateAutogeneratedItems = new HashSet<TemplateAutogeneratedItems>();
            TemplateSites = new HashSet<TemplateSites>();
        }

        public int SiteId { get; set; }
        public string BaseUrl { get; set; }
        public string Sid { get; set; }
        public int LanguageId { get; set; }
        public bool? Visibility { get; set; }

        public Languages Language { get; set; }
        public ICollection<BannerSites> BannerSites { get; set; }
        public ICollection<LeaguePriority> LeaguePriority { get; set; }
        public ICollection<LeagueVisibility> LeagueVisibility { get; set; }
        public ICollection<PredefinedCouponSites> PredefinedCouponSites { get; set; }
        public ICollection<SportPriority> SportPriority { get; set; }
        public ICollection<SportVisibility> SportVisibility { get; set; }
        public ICollection<TemplateAutogeneratedItems> TemplateAutogeneratedItems { get; set; }
        public ICollection<TemplateSites> TemplateSites { get; set; }
    }
}
